spring.application.name=chat-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp_chat
spring.datasource.username=postgres
spring.datasource.password=haris123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
